service: cesiones-services
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

custom:

  stages:
    dev:
      
      ENV: 'dev'
      REGION : 'us-east-2'
      SECRET_NAME_DB: 'dev/mysql'
      BUCKET_S3: 'arrayanfilesqa'
      SECRET_NAME_SII: 'sii/simpli'
      SECRET_DB_ARN: 'arn:aws:secretsmanager:us-east-2:746907585706:secret:dev/mysql-4oEUh1'
      SECRET_SII_ARN:  'arn:aws:secretsmanager:us-east-2:746907585706:secret:sii/simpli-KD5H84'
      DIAS_CERTF: 10
    
    prod:

      ENV: 'prod'
      REGION : 'us-east-2'
      SECRET_NAME_DB: 'prodLemuRDS'
      BUCKET_S3: 'arrayanfilesprod'
      SECRET_NAME_SII: 'sii/simpli'
      SECRET_DB_ARN: 'arn:aws:secretsmanager:us-east-2:746907585706:secret:prodLemuRDS-7PU8km'
      SECRET_SII_ARN:  'arn:aws:secretsmanager:us-east-2:746907585706:secret:sii/simpli-KD5H84'
      DIAS_CERTF: 10


resources:
  
  Resources:

    ## topic principal donde se envian los eventos de las cesiones obtenidas
    GetCesionesTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: GetCesionesTopic-${self:custom.stages.${opt:stage}.ENV}
        TopicName: GetCesionesTopic-${self:custom.stages.${opt:stage}.ENV}    


    ## topico que recibe los eventos y maneja el router para el guardado
    DbInsertTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: DbInsertTopic-${self:custom.stages.${opt:stage}.ENV}
        TopicName: DbInsertTopic-${self:custom.stages.${opt:stage}.ENV}

    ## role que tiene acceso a los secretos de la base de datos y de la clave de simpli del sii
    ## podra evaluar si es necesario publicar el mensaje en los demas 
    GetCesionesRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: GetCesionesRole-${self:custom.stages.${opt:stage}.ENV}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: cesionServicePolicyDocument-${self:custom.stages.${opt:stage}.ENV}
            PolicyDocument: 
              Version: '2012-10-17'
              Statement:

                ## simpli sii secrets
                - Effect: Allow
                  Action:
                    - 'secretsmanager:GetSecretValue'
                  Resource: ${self:custom.stages.${opt:stage}.SECRET_SII_ARN}
                
                ## database secrets
                - Effect: Allow
                  Action:
                    - 'secretsmanager:GetSecretValue'
                  Resource: ${self:custom.stages.${opt:stage}.SECRET_DB_ARN}
                
                ## permitir publicar en el topic
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: !Ref GetCesionesTopic
          
      
    ConsumerProcessCesionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ConsumerProcessCesionRole-${self:custom.stages.${opt:stage}.ENV}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: ConsumerProcessCesionRolePolicyDocument-${self:custom.stages.${opt:stage}.ENV}
            PolicyDocument: 
              Version: '2012-10-17'
              Statement:

                ## permitir obtener los secretos de la db
                - Effect: Allow
                  Action:
                    - 'secretsmanager:GetSecretValue'
                  Resource: ${self:custom.stages.${opt:stage}.SECRET_DB_ARN}
                
                ## permitir obtener los secretos de simpli sii
                - Effect: Allow
                  Action:
                    - 'secretsmanager:GetSecretValue'
                  Resource: ${self:custom.stages.${opt:stage}.SECRET_SII_ARN}
                
                ## subscribirse al SNS topic donde seran publicados los eventos
                ## que luego de ser procesados para guardase(HistorialCesion,AEC,Certificado,PDF Factura)
                - Effect: Allow
                  Action:
                    - "sns:ListSubscriptionsByTopic"
                    - "sns:Subscribe"
                  Resource: !GetAtt GetCesionesTopic.TopicArn

                ## permitir publicar eventos en el topico que manejara la insercion de los registros
                ## en base a un parametro
                - Effect: Allow
                  Action:
                    - "sns:Publish"
                  Resource: !GetAtt DbInsertTopic.TopicArn
                
                ## acceso al bucket s3 para subir archivos (certificado, AEC, PDF Facturas)
                - Effect: Allow
                  Action: "s3:PutObject"
                  Resource: [
                    "arn:aws:s3:::${self:custom.stages.${opt:stage}.BUCKET_S3}/aec_files/*",
                    "arn:aws:s3:::${self:custom.stages.${opt:stage}.BUCKET_S3}/certificados_cesion/*",
                    "arn:aws:s3:::${self:custom.stages.${opt:stage}.BUCKET_S3}/facturas_pdf/*",
                  ]
      
    DBAccessRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: DBAccessRole-${self:custom.stages.${opt:stage}.ENV}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: DBAccessRolePolicyDocument-${self:custom.stages.${opt:stage}.ENV}
            PolicyDocument: 
              Version: '2012-10-17'
              Statement:

                ## permitir obtener los secretos de la db
                - Effect: Allow
                  Action:
                    - 'secretsmanager:GetSecretValue'
                  Resource: ${self:custom.stages.${opt:stage}.SECRET_DB_ARN}

                ## permitir publicar eventos en el topico que manejara la insercion de los registros
                ## en base a un parametro
                - Effect: Allow
                  Action:
                    - "sns:ListSubscriptionsByTopic"
                    - "sns:Subscribe"
                  Resource: !GetAtt DbInsertTopic.TopicArn
                

functions:

  ## funcion lambda para obtener las cesiones del dia de simpli
  ## necesita acceder a los secretos de db y a la clave de simpli del sii
  getCesionesSimpli:
    handler: handler.get_cesiones_simpli
    environment:
        REGION_SECRET : ${self:custom.stages.${opt:stage}.REGION}
        SECRET_NAME_SII : ${self:custom.stages.${opt:stage}.SECRET_NAME_SII}
        SECRET_NAME_DB : ${self:custom.stages.${opt:stage}.SECRET_NAME_DB}
        SNS_TOPIC_ARN : !Ref GetCesionesTopic
    role : 
      Fn::Sub:
        - arn:aws:iam::${aws:accountId}:role/${RoleName}
        - RoleName: GetCesionesRole-${self:custom.stages.${opt:stage}.ENV}
    timeout: 30
    events:
      - schedule: 
          rate: cron(*/5 5-22 ? * MON-FRI *)
          enabled: false
          input:
            dias: 1
            tipo_consulta: 2
  
  ## procesa el evento de GetCesionesTopic para guardar en historial cesiones
  ## tiene acceso a los secretos de db y suscribirse al topico GetCesionesTopic
  saveCesionInDb:
      handler: handler.insert_hc_db
      environment:
        REGION_SECRET : ${self:custom.stages.${opt:stage}.REGION}
        SECRET_NAME_DB : ${self:custom.stages.${opt:stage}.SECRET_NAME_DB}
        SNS_TOPIC_ARN :  !Ref GetCesionesTopic
      role : 
        Fn::Sub:
          - arn:aws:iam::${aws:accountId}:role/${RoleName}
          - RoleName: ConsumerProcessCesionRole-${self:custom.stages.${opt:stage}.ENV}
      dependsOn:
        - "GetCesionesTopic"
        - "DbInsertTopic"
      events:
        - sns:
            displayName: Guarda el registro en la DB en historial_cesiones cuando un evento en publicado en GetCesionesTopic
            topicName: GetCesionesTopic
            arn: { "Fn::GetAtt": ["GetCesionesTopic", "TopicArn"] }

  ## funcion que procesa mensajes publicados en el getCesionesTopic para luego extraer los AEC(xml)
  ## debe tener permisos para acceder al topico getCesionesTopic y publicar en el topico (DbInsertTopic) para que sea guardado el AEC
  getAecXMLFile:
      handler: handler.get_aec_file
      environment:
        SUBDIR: 'aec_files'
        REGION_SECRET : ${self:custom.stages.${opt:stage}.REGION}
        BUCKET_NAME : ${self:custom.stages.${opt:stage}.BUCKET_S3}
        SECRET_NAME_SII : ${self:custom.stages.${opt:stage}.SECRET_NAME_SII}
        SNS_TOPIC_ARN :  !Ref DbInsertTopic
      role : 
        Fn::Sub:
          - arn:aws:iam::${aws:accountId}:role/${RoleName}
          - RoleName: ConsumerProcessCesionRole-${self:custom.stages.${opt:stage}.ENV}
      dependsOn:
        - "GetCesionesTopic"
        - "DbInsertTopic"
      events:
        - sns:
            displayName: Extrae los AEC cuando un evento es publicado en GetCesionesTopic
            topicName: GetCesionesTopic
            arn: { "Fn::GetAtt": ["GetCesionesTopic", "TopicArn"] }
  
  ## funcion que procesa mensajes publicados en el getCesionesTopic para luego extraer los El certificado de Cesion
  ## debe tener permisos para acceder al topico getCesionesTopic y publicar en el topico (DbInsertTopic) para que sea guardado el Certificado
  getCertificadoCesion:
      handler: handler.get_certificado_cesion
      environment:
        SUBDIR: 'certificados_cesion'
        BUCKET_NAME : ${self:custom.stages.${opt:stage}.BUCKET_S3}
        REGION_SECRET : ${self:custom.stages.${opt:stage}.REGION}
        SECRET_NAME_SII : ${self:custom.stages.${opt:stage}.SECRET_NAME_SII}
        SNS_TOPIC_ARN :  !Ref DbInsertTopic
        DAYS : ${self:custom.stages.${opt:stage}.DIAS_CERTF}
      role : 
        Fn::Sub:
          - arn:aws:iam::${aws:accountId}:role/${RoleName}
          - RoleName: ConsumerProcessCesionRole-${self:custom.stages.${opt:stage}.ENV}
      dependsOn:
        - "GetCesionesTopic"
        - "DbInsertTopic"
      events:
        - sns:
            displayName: Extrae los certificados de cesion cuando un evento es publicado en GetCesionesTopic
            topicName: GetCesionesTopic
            arn: { "Fn::GetAtt": ["GetCesionesTopic", "TopicArn"] }

      layers:
        - "arn:aws:lambda:us-east-2:746907585706:layer:wkhtmltox-01264:2"

  ## funcion para generar el PDF de la factura luego que sea extraido el AEC(XML)
  ## debe tener acceso al bucket para guardar el archivo y obtener el AEC del bucket
  ## debe poder subscribirse al topico que guarda el aec en base de datos y tambien generar un mensaje para que sea guardado el registro
  generatePDFCesion:
      handler: handler.generatePDFCesion
      environment:
        REGION_SECRET : ${self:custom.stages.${opt:stage}.REGION}
        BUCKET_NAME : ${self:custom.stages.${opt:stage}.BUCKET_S3}
        SUBDIR: 'facturas_pdf'
        SNS_TOPIC_ARN :  !Ref DbInsertTopic
      role : 
        Fn::Sub:
          - arn:aws:iam::${aws:accountId}:role/${RoleName}
          - RoleName: ConsumerProcessCesionRole-${self:custom.stages.${opt:stage}.ENV}
      dependsOn:
        - "GetCesionesTopic"
        - "DbInsertTopic"
      events:
        - sns:
            displayName: Procesar el evento luego de que se descargar el AEC
            topicName: DbInsertTopic
            arn: { "Fn::GetAtt": ["DbInsertTopic", "TopicArn"] }
      
      layers:
        - "arn:aws:lambda:us-east-2:746907585706:layer:wkhtmltox-01264:2"

  ## funcion para generar el manejo de los eventos en la base de datos
  ## debe tener acceso a la base de datos (secreto)
  insertRecordDb:
      handler: handler.insertRecordDb
      environment:
        REGION_SECRET : ${self:custom.stages.${opt:stage}.REGION}
        SECRET_NAME_DB : ${self:custom.stages.${opt:stage}.SECRET_NAME_DB}
        BUCKET_NAME : ${self:custom.stages.${opt:stage}.BUCKET_S3}
        SUBDIR: 'facturas_pdf'
      role : 
        Fn::Sub:
          - arn:aws:iam::${aws:accountId}:role/${RoleName}
          - RoleName: ConsumerProcessCesionRole-${self:custom.stages.${opt:stage}.ENV}
      dependsOn:
        - "DbInsertTopic"
      events:
        - sns:
            displayName: Procesar el evento de guardado
            topicName: DbInsertTopic
            arn: { "Fn::GetAtt": ["DbInsertTopic", "TopicArn"] }
      
      layers:
        - "arn:aws:lambda:us-east-2:746907585706:layer:wkhtmltox-01264:2"

outputs:
  GetCesionesTopicArn:
    Value:
      Fn::GetAtt: [GetCesionesTopic, TopicArn]

  DbInsertTopic:
    Value:
      Fn::GetAtt: [DbInsertTopic, TopicArn]

plugins:
  - serverless-python-requirements

package:
  patterns:
    - "!env/**"